### ISSUE TITLE
on itemSelected requires  stopPropagation in order to prevent clicking another item/button behind

### ISSUE THREAD

**Issue by sabrio** [kadoshms/ionic2-autocomplete#75]
I am having issue with `(itemSelect)` while I am select an item, it also triggers a click behind the list. Is there a way to event.stopPropagation()?

**Comment by kadoshms** [comment]
Unfortunately not in the current version, but I will add a support for that in the next release.

**Comment by kadoshms** [comment]
fixed in 64063f45dba0652088b0adc6686653f96d631cf1

**Comment by sabrio** [comment]
@kadoshms the issue seems to occur again, I am testing it on Android and it does occur. Can you please return the event somehow?

**Comment by webmanblog** [comment]
@kadoshms confirmed, the issue is still outstanding, at least on Android platform..

**Comment by JahBrewski** [comment]
@kadoshms Also seeing this bug. Is there a fix? This almost makes the plugin unusable.

**Comment by renanmoraes** [comment]
@kadoshms  Really still occurs
